### ISSUE TITLE
你好，这个项目还有开发的意向么，现在只能对项目查看，可以增加一些功能么，或者可以一起开发

### ISSUE THREAD

**Issue by Fengtianhe** [hypers/JiraAgileApp#1]

**Comment by simonguo** [comment]
最近一直在忙其他事情，目前满足自己使用没什么问题，也没有人提问题，所以也就没有更新。

如果你有好的想法可以提出，也可以 PR一起开发 , 我会长期支持。

**Comment by Fengtianhe** [comment]
1、现在的app中是按照仓库去分类，我认为可以有个dashboard

- [ ] 指派给我的
- [ ] 我关注的

2、jira 和 confluence 是可以关联的系统, 也可以把 confluence 中的空间，wiki 同步到这里
3、现在对任务得操作只限制于记录工作状态，可以增加 指派，修改状态，等操作
4、可以创建，编辑

ps：我下了一个jira mobile ent 感觉做的比较丑😀

**Comment by simonguo** [comment]
3和4相对来说比较好处理，也是比较硬性的需求，优先级可以高一些，你如果有时间可以先支持一下。  
1.这个需要 UI 设计,是一个体验上的改进，可以放在随后。
2.可以暂时不考虑，confluence 官方出了一个 Server 版本，可以满足所有需求。
